### ISSUE TITLE
Provide option to remove or customize `pr*-` prefix

### ISSUE THREAD

**Issue by claytoncollie** [gavv/pull-request-artifacts#133]
This would be nice to have. 

I am naming my artifact something very specific and would like to remove this extra prefix added by the action. 

Is this possible right now?

**Comment by gavv** [comment]
Hi, thanks for suggestion!

It was not possible. I've just tagged a new major release (v2) that implements it.

`artifacts-dir` option is now deprecated, and there is now new option `artifacts-prefix`. By default, that option is set to `prNNN-` (where NNN is PR number). You can set it to different string, including empty string.

Implemented in this commit: 1f58dc37e72cc351ec62c32186120c7baeeee955

See also #62.

Feel free to reopen issue if I'm missing something.
